In [ ]:
i=1
while i<5:
    if i==3:
            continue
    print(i,end=" ")
    i = i + 1

1 2 

In [ ]:
i=1
while i<3:
    j=0
    while j<5:
        j = j +1
        if j==3:
            continue
        print(j,end=" ")
    i = i +1

In [ ]:
i=1
while i<3:
    j=0
    while j<5:
        j = j+1
        if j==3:
            continue
        print(j,end=" ")
    i = i+1


In [ ]:
i=1
while i<3:
    j=0
    while j<5:
        j = j +1
        if j==3:
            continue
        print(j,end=" ")
    i = i +1


In [ ]:
n = int(input())
for i in range(1,n+1):
    temp = n
    for j in range(1,i):
        print(temp,end="")
        temp = temp -1
    for j in range(1,(2*n) - (2*i) + 2):
        print(n-i+1,end="")
    for j in range(1,i):
        temp = temp+1
        print(temp,end="")
    print()
for i in range(n-1,0,-1):
    temp = n
    for j in range(1,i):
        print(temp,end="")
        temp = temp - 1 
    for j in range(1,(2*n) - (2*i) + 2):
        print(n-i+1,end="")
    for j in range(1,i):
        temp = temp+1
        print(temp,end="")
    print()

In [2]:
number = int(input("Enter any number: "))
isPrime= True
if number > 1: 
    for i in range(2, number):
        if (number % i) == 0: 
            isPrime= False
        break
if(number<=1): 
    print("Is Not Prime")
elif(isPrime):
    print("Is Prime")
else:
    print("Is Not Prime")


Enter any number: 5
Is Prime


In [14]:
for con in "string":
    if con == "r":
        pass
    print(con)
    
if 3 not in [1,2,4,3,5]:
    print("true")

s
t
r
i
n
g


In [15]:
lst = []
for x in range(3):
    y = int(input())
    lst.append(y)
print(lst)

5
6
5
2
4
8
[6, 5, 2, 4, 8]


In [16]:
list = []
for i in range(3):
    y = int(input())
    list.append(y)
print(list)

5
2
4
[5, 2, 4]


In [30]:
#square root 
n = int(input())
l = n**(1/2)
print(l)

9
3.0


In [34]:
#square root ny newtons method
def newtonsqrt(n):
    approx = 0.5*n
    better = 0.5*(approx + n/approx)
    while better != approx:
        approx = better
        better = 0.5*(approx + n/approx)
    return approx
print("the square root is:",newtonsqrt(int(input())))

225
the square root is: 15.0


In [29]:
#to print all prime numbers in a given range
lower = int(input())
upper = int(input())
for i in range(lower,upper+1):
    if i>1:
        for x in range(2,i):
            if (i%x)==0:
                break
        else:
            print(i)

1
10
2
3
5
7


In [3]:
#2d array
from numpy import array
data = [[11,22],[33,44],[55,66]]
data = array(data)
print(data)
print(type(data))


[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [6]:
from numpy import array
data = ([11,22,33,44,55])
print(data[4])
print(data[-1])

55
55


In [9]:
from numpy import array
data = array([[11,22],[33,44],[55,66]])
print(data[0,0])


11


In [13]:
#simple slicing
from numpy import array
data = array([11,22,33,44,55,66])
print(data[:])
print(data[0:-2])

[11 22 33 44 55 66]
[11 22 33 44]


In [26]:
#separate data
data = array([[11,22,33],[44,55,66],[77,88,99]])
x,y = data[:,:],data[:,:]
print(x)
print(y)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [27]:
#array creation 
cars = ["ford","volvo"]
cars.append("honda")
print(cars)

#to remove an element using pop
cars = ["honda","ford"]
cars.pop(1)
print(cars)

['ford', 'volvo', 'honda']
['honda']


In [32]:
import numpy as np
arr = np.array([[1,2,3],[4,2,5],[4,2,6],[3,4,5]])
print("array is a type:",type(arr))
print("number of dimensions:",arr.ndim)
print("shape of array:",arr.shape)

array is a type: <class 'numpy.ndarray'>
number of dimensions: 2
shape of array: (4, 3)


In [ ]:
#how to convert list to array
#use numpy.array()
#or use numpy.asarray()

In [6]:
def nsqrt(n):
    i=0.5*n
    j=0.5*(i+n/i)
    while j!=i:
        i=j
        j=0.5*(i+n/i)
    return i
print(nsqrt(100))

10.0


In [1]:
def func(a):
    a = a + 10
    return a
a = 5
func(a)
print(a)

5


In [2]:
def square(a):
    ans  = a*a
    return  ans

a = 4
a = square(a)
print(a)

16


In [12]:
a=14
def f():
    global a
    a=12
print(a)
f()

14


In [18]:
Fahrenheit = int(input())
E = int(input())
W = int(input())
while Fahrenheit <= E:
    Fahrenheit_to_Celsius = (((Fahrenheit - 32) * 5) / 9)
    print(Fahrenheit, int(Fahrenheit_to_Celsius))
    Fahrenheit = Fahrenheit + W

14


In [4]:
#pop is used for removing an element by providing its index value 
li = [5,2,6,8]
li.pop(2)
print(li)

[5, 2, 8]


In [12]:
def change(li):
    li[1] = li[1] + 2
    li = [3,3,3,4,5]
li = [1,2,3,4,5]
change(li)
print(li)


[1, 4, 3, 4, 5]


In [1]:
print('Welcome to AskPython Quiz')
answer=input('Are you ready to play the Quiz ? (yes/no) :')
score=0
total_questions=3
 
if answer.lower()=='yes':
    answer=input('Question 1: What is your Favourite programming language?')
    if answer.lower()=='python':
        score += 1
        print('correct')
    else:
        print('Wrong Answer :(')
 
 
    answer=input('Question 2: Do you follow any author on AskPython? ')
    if answer.lower()=='yes':
        score += 1
        print('correct')
    else:
        print('Wrong Answer :(')
 
    answer=input('Question 3: What is the name of your favourite website for learning Python?')
    if answer.lower()=='askpython':
        score += 1
        print('correct')
    else:
        print('Wrong Answer :(')
 
print('Thankyou for Playing this small quiz game, you attempted',score,"questions correctly!")
mark=(score/total_questions)*100
print('Marks obtained:',mark)
print('BYE!')

Welcome to AskPython Quiz
Are you ready to play the Quiz ? (yes/no) :yes
Question 1: What is your Favourite programming language?python
correct
Question 2: Do you follow any author on AskPython? no
Wrong Answer :(
Question 3: What is the name of your favourite website for learning Python?Askpython
correct
Thankyou for Playing this small quiz game, you attempted 2 questions correctly!
Marks obtained: 66.66666666666666
BYE!
